#!/bin/bash

# myextract version 1.00 Janvier 2025 par Thierry Le Gall
# extraire un block d'un fichier
# syntaxe : myextract "FILE" "BEGIN" "END"

awk -v begin="$2" -v end="$3" '$0 ~ end {f=0} $0 ~ begin {f=1} f {print}' $1
