#!/bin/bash

# mygrep version 1.00 Janvier 2025 par Thierry Le Gall
# rechercher dans une liste de répertoires et de fichiers
# syntaxe : mygrep "OPTIONS" "PATTERN" "FILTER" "LIST"

OPTIONS=$1
PATTERN=$2
FILTER=$3
LIST=$4

[ "$LIST" = '' ] && exit

GREP="grep -aR --exclude=*.swp $OPTIONS"

if   [ "$PATTERN" != '' ] && [ "$FILTER"  = '' ] ; then $GREP    "$PATTERN" $LIST
elif [ "$PATTERN" != '' ] && [ "$FILTER" != '' ] ; then $GREP    "$PATTERN" $LIST | grep -av $OPTIONS "$FILTER"
elif [ "$PATTERN"  = '' ] && [ "$FILTER" != '' ] ; then $GREP -v "$FILTER"  $LIST
fi
