#!/bin/bash

# mygrep version 1.00 Janvier 2025 par Thierry Le Gall

OPTIONS=$1
PATTERN=$2
FILTER=$3
LIST=$4

[ "$LIST" = '' ] && exit

OPTIONS="$OPTIONS -aR --exclude=*.swp"

if   [ "$PATTERN" != '' ] && [ "$FILTER"  = '' ] ; then grep    $OPTIONS "$PATTERN" $LIST
elif [ "$PATTERN"  = '' ] && [ "$FILTER" != '' ] ; then grep -v $OPTIONS "$FILTER"  $LIST
elif [ "$PATTERN" != '' ] && [ "$FILTER" != '' ] ; then grep    $OPTIONS "$PATTERN" $LIST | grep -av "$FILTER"
fi
