#!/bin/bash

# myverif version 1.00 Janvier 2025 par Thierry Le Gall
# fonction qui peut être complétée avec d'autres types de langage
# syntaxe : myverif "FILE"

FILE=$1

case $(head -n1 "$FILE") in # test de la première ligne du fichier
  sh) TYPE=sh ;;
perl) TYPE=sh ;;
   *) case $(echo "$FILE" | awk -F. '{print $NF}') in # test de l'extention du fichier .X
            sh) TYPE=sh ;;
      pl|pm|tk) TYPE=perl ;;
      esac
esac

case $TYPE in
  sh) shellcheck "$FILE" -W0 -e SC2059,SC2086 && echo "$FILE syntax OK" ;;
perl) perl -c    "$FILE" ;;
esac
