#!/bin/bash

# myverif version 1.00 Janvier 2025 par Thierry Le Gall
# fonction qui peut être complétée avec d'autres types de langage
# syntaxe : myverif "FILE"

fct_sh   () { shellcheck "$FILE" -W0 -e SC2059,SC2086 && echo "$FILE syntax OK" ; }
fct_perl () { perl -c    "$FILE" ; }

FILE=$1

case ${FILE##*.} in # test de l'extention du fichier .X
      sh) fct_sh ;;
pl|pm|tk) fct_perl ;;
       *) case $(grep '#!' "$FILE" | head -n1) in # test de la ligne #!
            *sh*) printf fct_sh ;;
          *perl*) printf fct_perl ;;
          esac ;;
esac
